OPENAI_APIKEY_CS="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"
HUGGINGFACE_APIKEY="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"
COHERE_APIKEY="913XB981bOqRwnYlSFdEKPqo0Kx3GQd5VLwqygTD"
PINECONE_API_KEY="b1c1c1a4-30b7-4891-a0a0-15947bdab7c7"
PINECONE_API_KEY_SAM = "b57d6fe0-dc75-498e-bae1-cd005e53dcaf"